### ISSUE TITLE
Creating Char does not insert into Database

### ISSUE THREAD

**Issue by ohaidan** [FiveEYZ/esx_kashacter#33]
I've tried for **days** now, however, no luck. 
Whenever I load in, I create a character, however, it doesn't add that character to our database. We get this error:

```
SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed: Argument at index 1 was null.
> callback (@esx_identity/server/main.lua:88)
> ref (@esx_identity/server/main.lua:47)
>  (@mysql-async/mysql-async.js:15543)```

I've had a look myself, and cannot figure it out

**Comment by ohaidan** [comment]
**oh shit. IGNORE THIS I MANAGED TO FIX THE CODE**

**Comment by Heavens-c** [comment]
how did you manage to fix it ??

**Comment by mascotte-scripts** [comment]
> how did you manage to fix it ??

Had the exact same error, spoke with a buddy of mine and what he said was:

"You're not passing a player server id 2f7a49e6 is TriggerClientEventInternal or TriggerClientEvent" - the client function in this instance being the esx_identity function that checks whether there's data already in the database to the identifier the player is using. Think of it as I'm handing you my ID card but my ID card doesn't have an ID number on it. 

So the problem is that we're not passing any data to the identifier variable, so it coughs back an error because it doesn't actually know what we're trying to pass to it. 

So hopefully @jrence that's some help to you :)
